#!/usr/bin/env python3
"""Train a tiny autoencoder on a synthetic 'normal' periodic signal,
quantize to int8, and emit a C source file (model.cpp) ready to compile
into the Zephyr app.

Run:
    ../../../.venv-ml/bin/python train.py

Outputs:
    model.tflite           — the quantized model
    ../src/model.cpp       — C array (extern const unsigned char g_model[])
    ../src/model.hpp       — header with the extern declaration

The 'normal' signal is the sum of two sinusoids plus a little noise. The
autoencoder learns to reconstruct windows of this. At inference time on the
MCU, the reconstruction MSE is the anomaly score: low for windows that look
like the training distribution, high when the signal is corrupted.
"""

from __future__ import annotations

import os
import pathlib
import sys

import numpy as np
import tensorflow as tf

# ---------- config ----------------------------------------------------------

WINDOW       = 32        # samples per input window
BOTTLENECK   = 4         # latent dim — controls how much info the AE can keep
N_TRAIN      = 8000      # number of training windows
N_VAL        = 1000      # number of validation windows
EPOCHS       = 60
BATCH        = 64
SEED         = 42

HERE         = pathlib.Path(__file__).parent
TFLITE_OUT   = HERE / "model.tflite"
CPP_OUT      = HERE.parent / "src" / "model.cpp"
HPP_OUT      = HERE.parent / "src" / "model.hpp"

# ---------- synthetic signal ------------------------------------------------

def make_normal_window(rng: np.random.Generator) -> np.ndarray:
    """One window of the 'normal' signal: sum of two sinusoids + light noise.

    The phase is randomized per window so the AE doesn't trivially memorize
    one waveform. Frequencies are fixed so 'normal' has a definite shape.
    """
    t = np.linspace(0.0, 1.0, WINDOW, endpoint=False, dtype=np.float32)
    phase1 = rng.uniform(0.0, 2 * np.pi)
    phase2 = rng.uniform(0.0, 2 * np.pi)
    sig = (np.sin(2 * np.pi * 1.0 * t + phase1)
           + 0.3 * np.sin(2 * np.pi * 3.0 * t + phase2)
           + 0.05 * rng.standard_normal(WINDOW))
    return sig.astype(np.float32)

def make_dataset(n: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    return np.stack([make_normal_window(rng) for _ in range(n)])

# ---------- model -----------------------------------------------------------

def build_autoencoder() -> tf.keras.Model:
    """Tiny dense AE: 32 -> 16 -> 8 -> 4 -> 8 -> 16 -> 32.

    Kept small on purpose:
      - fits comfortably in <2 KB once int8-quantized
      - inference is a few hundred microseconds at 170 MHz
      - bottleneck of 4 forces it to learn the 'shape' of a normal window
        rather than memorize amplitude/phase exactly
    """
    inp = tf.keras.Input(shape=(WINDOW,), dtype=tf.float32)
    x = tf.keras.layers.Dense(16, activation="relu")(inp)
    x = tf.keras.layers.Dense(8, activation="relu")(x)
    z = tf.keras.layers.Dense(BOTTLENECK, activation="relu", name="bottleneck")(x)
    x = tf.keras.layers.Dense(8, activation="relu")(z)
    x = tf.keras.layers.Dense(16, activation="relu")(x)
    out = tf.keras.layers.Dense(WINDOW, activation="linear")(x)
    return tf.keras.Model(inp, out, name="anomaly_ae")

# ---------- quantization helpers --------------------------------------------

def to_tflite_int8(model: tf.keras.Model, repr_data: np.ndarray) -> bytes:
    """Convert a Keras model to int8-quantized TFLite using a representative
    dataset. Both input and output are int8 so on-MCU we don't carry a float
    runtime path."""
    def repr_gen():
        for i in range(min(500, len(repr_data))):
            yield [repr_data[i:i + 1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = repr_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()

def write_c_array(tflite_bytes: bytes, cpp_path: pathlib.Path,
                  hpp_path: pathlib.Path) -> None:
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    n = len(tflite_bytes)
    lines = [
        "/* Generated by apps/ai_anomaly/train/train.py — DO NOT EDIT BY HAND */",
        "#include \"model.hpp\"",
        "",
        f"alignas(8) const unsigned char g_model[{n}] = {{",
    ]
    for i in range(0, n, 12):
        chunk = tflite_bytes[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int g_model_len = {n};")
    cpp_path.write_text("\n".join(lines) + "\n")

    hpp_path.write_text(
        "/* Generated by apps/ai_anomaly/train/train.py — DO NOT EDIT BY HAND */\n"
        "#ifndef MODEL_HPP\n"
        "#define MODEL_HPP\n"
        "extern const unsigned char g_model[];\n"
        "extern const unsigned int  g_model_len;\n"
        "#endif\n"
    )

# ---------- main ------------------------------------------------------------

def main() -> int:
    np.random.seed(SEED)
    tf.random.set_seed(SEED)

    print("Generating synthetic normal-signal dataset…")
    x_train = make_dataset(N_TRAIN, SEED)
    x_val   = make_dataset(N_VAL,   SEED + 1)
    print(f"  train: {x_train.shape}  range=[{x_train.min():.2f}, {x_train.max():.2f}]")

    model = build_autoencoder()
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3), loss="mse")
    print(model.summary())

    print(f"Training for {EPOCHS} epochs…")
    model.fit(x_train, x_train,
              validation_data=(x_val, x_val),
              epochs=EPOCHS, batch_size=BATCH, verbose=2)

    # Spot-check accuracy on normal vs corrupted input -----------------------
    recon = model.predict(x_val, verbose=0)
    normal_mse = np.mean((x_val - recon) ** 2, axis=1)

    rng = np.random.default_rng(SEED + 2)
    x_anom = x_val.copy()
    # inject a 0.5-amplitude pulse in the middle of each window
    x_anom[:, WINDOW // 2 - 1:WINDOW // 2 + 2] += 0.5
    recon_anom = model.predict(x_anom, verbose=0)
    anom_mse = np.mean((x_anom - recon_anom) ** 2, axis=1)

    print()
    print("Reconstruction MSE summary (lower = looks like training data):")
    print(f"  normal windows  : mean={normal_mse.mean():.5f}  "
          f"p95={np.quantile(normal_mse, 0.95):.5f}")
    print(f"  +pulse windows  : mean={anom_mse.mean():.5f}  "
          f"p05={np.quantile(anom_mse, 0.05):.5f}")
    print(f"  separation ratio: {anom_mse.mean() / normal_mse.mean():.1f}x")

    print()
    print("Quantizing to int8 + converting to TFLite…")
    tflite_bytes = to_tflite_int8(model, x_train)
    TFLITE_OUT.write_bytes(tflite_bytes)
    print(f"  wrote {TFLITE_OUT}  ({len(tflite_bytes)} bytes)")

    print("Emitting C source…")
    write_c_array(tflite_bytes, CPP_OUT, HPP_OUT)
    print(f"  wrote {CPP_OUT}")
    print(f"  wrote {HPP_OUT}")
    print()
    print("Done. Build the firmware with:")
    print("  west build -p auto -b nucleo_g474re apps/ai_anomaly -d build/ai_anomaly")
    return 0

if __name__ == "__main__":
    sys.exit(main())
