#!/usr/bin/env python3
"""Train a tiny MLP that ESTIMATES BATTERY CAPACITY (SOH) from a single
discharge voltage curve.

This is *regression*, not anomaly detection. Given a 32-point discharge
voltage curve, predict the Ah delivered during that cycle.

Why this matters: every BMS needs to know SOH (state of health = current
capacity / nominal capacity). It's the basis of "how much range is left in
this car / how long can this drone fly". Traditional methods do
coulomb-counting of full discharges or impedance spectroscopy; here we
learn the mapping directly from a partial-discharge curve.

Data: NASA PCoE Battery Dataset, same as `apps/ai_bms/`. We REUSE that
download — no need to re-fetch.

Run:
    apps/ai_bms_soh/train/train.py

Outputs:
    model.tflite
    ../src/model.cpp / model.hpp           — the int8 model
    ../src/cycles_db.cpp / cycles_db.h     — embedded cycles + ground-truth Ah
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
import scipy.io as sio
import tensorflow as tf

# ---------- config ----------------------------------------------------------

WINDOW       = 32
TRAIN_CELLS  = ["B0005", "B0006", "B0007"]
HOLDOUT_CELL = "B0018"     # not used during training; for evaluation + demo
EPOCHS       = 120
BATCH        = 32
SEED         = 42
V_MIN, V_MAX = 2.4, 4.3

# Capacity normalization range — outputs squashed to roughly [-1, +1] before
# int8 quantization. NASA cells are nominally 2 Ah and end-of-life ~1.4 Ah,
# so [1.0, 2.0] is a generous range.
CAP_MIN, CAP_MAX = 1.0, 2.0

HERE       = pathlib.Path(__file__).parent
DATA_DIR   = HERE.parent.parent / "ai_bms" / "train" / "data" / "5. Battery Data Set"
TFLITE_OUT = HERE / "model.tflite"
CPP_OUT    = HERE.parent / "src" / "model.cpp"
HPP_OUT    = HERE.parent / "src" / "model.hpp"
CYCLES_OUT = HERE.parent / "src" / "cycles_db.cpp"
CYCLES_HDR = HERE.parent / "src" / "cycles_db.h"

# ---------- data -----------------------------------------------------------

def load_discharge(cell_id):
    mat = sio.loadmat(DATA_DIR / f"{cell_id}.mat",
                       squeeze_me=True, struct_as_record=False)
    cycles = mat[cell_id].cycle
    out = []   # list of (voltage_curve_resampled, capacity, cycle_idx)
    di = 0
    for cy in cycles:
        if cy.type != "discharge":
            continue
        v = np.asarray(cy.data.Voltage_measured, dtype=np.float32)
        t = np.asarray(cy.data.Time, dtype=np.float32)
        cap = float(cy.data.Capacity)
        if v.size < 8:
            continue
        t_norm = (t - t[0]) / max(t[-1] - t[0], 1e-6)
        u = np.linspace(0.0, 1.0, WINDOW, dtype=np.float32)
        v_rs = np.interp(u, t_norm, v).astype(np.float32)
        out.append((v_rs, cap, di))
        di += 1
    return out

def collect(cells):
    curves, caps = [], []
    for cid in cells:
        rows = load_discharge(cid)
        curves.extend(r[0] for r in rows)
        caps.extend(r[1] for r in rows)
        print(f"  {cid}: {len(rows)} cycles, "
              f"cap [{min(r[1] for r in rows):.3f}..{max(r[1] for r in rows):.3f}] Ah")
    return np.stack(curves), np.array(caps, dtype=np.float32)

def normalize_v(v):
    return (v - V_MIN) / (V_MAX - V_MIN) * 2.0 - 1.0

def normalize_cap(c):
    return (c - CAP_MIN) / (CAP_MAX - CAP_MIN) * 2.0 - 1.0

def denormalize_cap(y):
    return (y + 1.0) / 2.0 * (CAP_MAX - CAP_MIN) + CAP_MIN

# ---------- model ----------------------------------------------------------

def build_regressor():
    inp = tf.keras.Input(shape=(WINDOW,), dtype=tf.float32)
    x = tf.keras.layers.Dense(32, activation="relu")(inp)
    x = tf.keras.layers.Dense(16, activation="relu")(x)
    x = tf.keras.layers.Dense(8,  activation="relu")(x)
    out = tf.keras.layers.Dense(1, activation="linear")(x)
    return tf.keras.Model(inp, out, name="bms_soh_mlp")

def to_tflite_int8(model, repr_data):
    def repr_gen():
        for i in range(min(500, len(repr_data))):
            yield [repr_data[i:i + 1].astype(np.float32)]
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = repr_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()

# ---------- emit C ---------------------------------------------------------

def write_model_c(tflite_bytes, cpp, hpp):
    n = len(tflite_bytes)
    cpp.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by apps/ai_bms_soh/train/train.py — DO NOT EDIT */",
        "#include \"model.hpp\"",
        "",
        f"alignas(8) const unsigned char g_model[{n}] = {{",
    ]
    for i in range(0, n, 12):
        chunk = tflite_bytes[i:i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int g_model_len = {n};")
    cpp.write_text("\n".join(lines) + "\n")
    hpp.write_text(
        "/* Generated — DO NOT EDIT */\n#ifndef MODEL_HPP\n#define MODEL_HPP\n"
        "extern const unsigned char g_model[];\n"
        "extern const unsigned int  g_model_len;\n"
        "#endif\n"
    )

def write_cycles_c(samples, cpp, hpp):
    cpp.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated — DO NOT EDIT */",
        "#include \"cycles_db.h\"",
        "",
        f"const unsigned int g_cycle_count = {len(samples)};",
        "const struct soh_cycle g_cycles[] = {",
    ]
    for s in samples:
        lines.append("    {")
        lines.append(f"        .name = \"{s['name']}\",")
        lines.append(f"        .cell = \"{s['cell']}\",")
        lines.append(f"        .index = {s['idx']},")
        lines.append(f"        .true_capacity_ah = {s['cap']:.4f}f,")
        lines.append("        .voltage_norm = {")
        for v in s['curve']:
            lines.append(f"            {v:+.6f}f,")
        lines.append("        },")
        lines.append("    },")
    lines.append("};")
    cpp.write_text("\n".join(lines) + "\n")
    hpp.write_text(
        "/* Generated — DO NOT EDIT */\n#ifndef CYCLES_DB_H\n#define CYCLES_DB_H\n"
        "#include <stddef.h>\n\n"
        "#define SOH_WINDOW 32\n\n"
        "struct soh_cycle {\n"
        "    const char  *name;\n"
        "    const char  *cell;\n"
        "    unsigned int index;\n"
        "    float        true_capacity_ah;\n"
        "    float        voltage_norm[SOH_WINDOW];\n"
        "};\n\n"
        "extern const unsigned int g_cycle_count;\n"
        "extern const struct soh_cycle g_cycles[];\n"
        "#endif\n"
    )

# ---------- main ----------------------------------------------------------

def main():
    if not DATA_DIR.exists():
        print(f"ERROR: NASA data not found at {DATA_DIR}", file=sys.stderr)
        print("Run apps/ai_bms/train/data download steps first.", file=sys.stderr)
        return 1

    np.random.seed(SEED)
    tf.random.set_seed(SEED)

    print("Loading NASA discharge cycles…")
    train_v, train_c = collect(TRAIN_CELLS)
    holdout_v, holdout_c = collect([HOLDOUT_CELL])

    train_v_n   = normalize_v(train_v)
    train_y     = normalize_cap(train_c)
    holdout_v_n = normalize_v(holdout_v)
    holdout_y   = normalize_cap(holdout_c)

    model = build_regressor()
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3), loss="mse",
                  metrics=["mae"])
    print(model.summary())

    print(f"Training {EPOCHS} epochs on {len(train_v_n)} cycles…")
    model.fit(train_v_n, train_y,
              validation_split=0.1,
              epochs=EPOCHS, batch_size=BATCH, verbose=2)

    # Evaluate on holdout cell --------------------------------------------
    pred_n = model.predict(holdout_v_n, verbose=0).flatten()
    pred = denormalize_cap(pred_n)
    err = pred - holdout_c
    mae = float(np.mean(np.abs(err)))
    rmse = float(np.sqrt(np.mean(err ** 2)))
    p95 = float(np.quantile(np.abs(err), 0.95))

    print()
    print(f"Holdout {HOLDOUT_CELL} regression performance:")
    print(f"  MAE  : {mae*1000:.1f} mAh  (mean absolute error)")
    print(f"  RMSE : {rmse*1000:.1f} mAh")
    print(f"  p95  : {p95*1000:.1f} mAh  (95th percentile of |error|)")
    print(f"  range: cap [{holdout_c.min():.3f} .. {holdout_c.max():.3f}] Ah, "
          f"so MAE / range = {mae / (holdout_c.max() - holdout_c.min()) * 100:.1f}%")

    # Pick demo cycles spanning the SOH range -----------------------------
    selected = []
    cap_targets = [
        ("early",  0,                            holdout_c[0]),
        ("mid",    len(holdout_c) // 2,          holdout_c[len(holdout_c) // 2]),
        ("aged",   len(holdout_c) - 1,           holdout_c[-1]),
    ]
    for name, idx, cap in cap_targets:
        selected.append({
            "name":  name,
            "cell":  HOLDOUT_CELL,
            "idx":   int(idx),
            "cap":   float(cap),
            "curve": holdout_v_n[idx].tolist(),
        })
    print()
    print("Embedded sample cycles for the firmware:")
    for s in selected:
        print(f"  {s['name']:<6} idx={s['idx']:3d}  true_cap={s['cap']:.4f} Ah")

    # Quantize + emit ------------------------------------------------------
    print("\nQuantizing to int8 + converting to TFLite…")
    tflite_bytes = to_tflite_int8(model, train_v_n)
    TFLITE_OUT.write_bytes(tflite_bytes)
    print(f"  wrote {TFLITE_OUT}  ({len(tflite_bytes)} bytes)")

    write_model_c(tflite_bytes, CPP_OUT, HPP_OUT)
    write_cycles_c(selected, CYCLES_OUT, CYCLES_HDR)
    print(f"  wrote {CPP_OUT}")
    print(f"  wrote {CYCLES_OUT}")
    print()
    print("Done. Build:")
    print("  west build -p auto -b nucleo_g474re apps/ai_bms_soh -d build/ai_bms_soh")
    return 0

if __name__ == "__main__":
    sys.exit(main())
